### ISSUE TITLE
delete console.log

### ISSUE THREAD

**Issue by ryoppippi** [fayez-nazzal/sveltekit-tweet#2]
Hi!

I tries this library, thank you.

Could you delete this console.log (https://github.com/fayez-nazzal/sveltekit-tweet/blob/aae20009939ab7f4048371ee149fc331a9dcabe6/src/lib/utils.server.ts#L86), because when we lauch dev server it is hard to see error log because of this giant tweet log.

**Comment by fayez-nazzal** [comment]
Thanks for trying the package @ryoppippi now it is updated

**Comment by ryoppippi** [comment]
Thank you!!
